#!/bin/bash
function usage() 
{
echo "-p 				-				Specify the password to check"
echo "Example:"
echo "tea -p 1234"

}

#Color variables
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
PURPLE='\033[0;34m'
CYAN='\033[0;35m'
LIGHTGRAY='\033[0;36m'
NC='\033[0m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
LIGHTORANGE='\033[1;33m'
LIGHTPURPLE='\033[1;34m'
LIGHTCYAN='\033[1;35m'
cat /home/hippi3c0w/tools/Tea/style
echo " "
echo " Made by Manu Alén - @hippi3c0w"
echo " "

if [[ $# -lt 2 ]];then
	usage
else
for passwords in $(cat /home/hippi3c0w/tools/Tea/tea_dictionary.txt)
do
	#checking
	searcher=`cat /home/hippi3c0w/tools/Tea/tea_dictionary.txt | grep $2`
	if [[ $searcher ]];then
		

		echo -e "${RED}THE PASSWORD YOU HAVE SELECTED EXISTS INTO SOME DICTIONARIES. PLEASE DON'T USE IT ${NC}"
		exit 0
		
	else

		echo -e "${GREEN} GOOD NEWS. YOUR PASSWORD [$2:$passwords] DOESN'T EXIST INTO DICTIONARIES ${NC}"
		if [[ $passwords == "EOF" ]];then
			exit 0
		fi

	fi

done
fi